name: CI

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - README.md
        - 
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - README.md

env:
  DEVELOPER_DIR: /Applications/Xcode_11.0.app/Contents/Developer

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Show Xcode version
      run: xcodebuild -version
      
      # ビルド実行
    - name: Build
      run: make build-debug
      
      # テスト実行
    - name: Run tests
      run: make test
