name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      
    # Xcode バージョン設定
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.3.app/Contents/Developer'
      
    - name: Show Xcode version
      run: xcodebuild -version
      
      # ビルド実行
    - name: Build
      run: xcodebuild
            -scheme Test
            -sdk iphonesimulator
            -configuration Debug
            build
            
      # テスト実行
    - name: Run tests
      run: xcodebuild
            -scheme Test
            -sdk iphonesimulator
            -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
            clean test
